// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <header>
//           <Link href={"/"}>index</Link>
//           &nbsp;
//           <Link href={"/search"}>search</Link>
//           &nbsp;
//           <Link href={"/book/1"}>book1</Link>
//         </header>
//         {children}
//       </body>
//     </html>
//   );
// }
import React from "react";
import "./globals.css";
import style from "./layout.module.css";
import Link from "next/link";

const Footer = async () => {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_API_SERVER_URL}/book`,
    {
      cache: "force-cache",
    }
  );

  if (!response.ok) {
    return <footer>제작 @Hwichan</footer>;
  }

  const books = await response.json();
  const bookCount = books.length;

  return (
    <footer>
      <div>제작 @Hwichan</div>
      <div>12개의 도서가 등록되어 있습니다</div>
    </footer>
  );
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html>
      <body>
        <div className={style.container}>
          <header>
            <Link href={"/"}>📚 ONEBITE BOOKS</Link>
          </header>
          <main>{children}</main>
          <footer>제작 Hwichan</footer>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
